### ISSUE TITLE
hash result changed a lot after bucket sized changed

### ISSUE THREAD

**Issue by lazywhite** [renstrom/go-jump-consistent-hash#12]
I think the benifit of consistent-hash is this: when bucket size changed, only a litte group of data need rebalanced

so I wrote a program to test this feature, but it shows that every number got remapped
```
func main(){
    rt := 0
    num := 10000
    for i:=0; i<num; i++{
        var a uint64 = 10000
        i1 := jump.Hash(a, 10)
        i2 := jump.Hash(a, 20)

        if i1 != i2{
            rt++
        }
    }

    fmt.Println(rt == num) // ********* true **********
}

```

**Comment by lithammer** [comment]
I'm not the paper author, I just ported the reference C++ implementation to Go. So I can't say much about the algorithm itself. I'm gonna have to to refer you to the paper[^1] for details.

```cpp
int32_t JumpConsistentHash(uint64_t key, int32_t num_buckets) {
  int64_t b = ­1, j = 0;
  while (j < num_buckets) {
    b=j;
    key = key * 2862933555777941757ULL + 1;
    j = (b + 1) * (double(1LL << 31) / double((key >> 33) + 1));
  }
  return b;
}
```

With that said. There's a "revamped" version called doublejump[^2] that supposedly fixes some of the shortcomings of the original implementation (e.g. not being able to remove nodes). However I have no personal experience from using it myself. 

[^1]: https://arxiv.org/pdf/1406.2294v1.pdf
[^2]: https://github.com/edwingeng/doublejump
