### ISSUE TITLE
Concurrency Issue

### ISSUE THREAD

**Issue by kpowers122** [renstrom/go-jump-consistent-hash#6]
Really appreciate this library, we use it a lot.

Just wanted to make others aware if you use the examples in highly concurrent code, you will want to create your own unique instance of the hashers rather than the constants in the library as you will get inconsistent results:

Instead of this:
`h := jump.HashString("127.0.0.1", 8, jump.CRC64)`

You would do this:
`h := jump.HashString("127.0.0.1", 8,  crc64.New(crc64.MakeTable(crc64.ECMA)))`

Just sharing for others.

**Comment by lithammer** [comment]
Hmm, good find. I suspect it's because the hasher is reset at the start of `HashString`, hmm 🤔
